

-- MySQL Script generated by MySQL Workbench
-- lun 08 ago 2022 11:56:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biografo_imaginario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biografo_imaginario` ;

-- -----------------------------------------------------
-- Schema biografo_imaginario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biografo_imaginario` DEFAULT CHARACTER SET utf8 ;
USE `biografo_imaginario` ;

CREATE USER 'dbwebapp'@'%' IDENTIFIED BY 'dbwebapp';
GRANT ALL PRIVILEGES ON biografo_imaginario.* TO 'dbwebapp'@'%';

-- -----------------------------------------------------
-- Table `biografo_imaginario`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biografo_imaginario`.`users` ;

CREATE TABLE IF NOT EXISTS `biografo_imaginario`.`users` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `is_admin` TINYINT NULL DEFAULT 0,
  `email` VARCHAR(128) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biografo_imaginario`.`objects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biografo_imaginario`.`objects` ;

CREATE TABLE IF NOT EXISTS `biografo_imaginario`.`objects` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `url` VARCHAR(128) NOT NULL,
  `users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_objects_users1_idx` (`users_username` ASC) VISIBLE,
  CONSTRAINT `fk_objects_users1`
    FOREIGN KEY (`users_username`)
    REFERENCES `biografo_imaginario`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biografo_imaginario`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biografo_imaginario`.`videos` ;

CREATE TABLE IF NOT EXISTS `biografo_imaginario`.`videos` (
  `id` INT NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `url` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `objects_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_objects1_idx` (`objects_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_objects1`
    FOREIGN KEY (`objects_id`)
    REFERENCES `biografo_imaginario`.`objects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biografo_imaginario`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biografo_imaginario`.`tags` ;

CREATE TABLE IF NOT EXISTS `biografo_imaginario`.`tags` (
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biografo_imaginario`.`users_has_videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biografo_imaginario`.`users_has_videos` ;

CREATE TABLE IF NOT EXISTS `biografo_imaginario`.`users_has_videos` (
  `users_username` VARCHAR(45) NOT NULL,
  `videos_id` INT NOT NULL,
  PRIMARY KEY (`users_username`, `videos_id`),
  INDEX `fk_users_has_videos_videos1_idx` (`videos_id` ASC) VISIBLE,
  INDEX `fk_users_has_videos_users1_idx` (`users_username` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_videos_users1`
    FOREIGN KEY (`users_username`)
    REFERENCES `biografo_imaginario`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_videos_videos1`
    FOREIGN KEY (`videos_id`)
    REFERENCES `biografo_imaginario`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biografo_imaginario`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biografo_imaginario`.`questions` ;

CREATE TABLE IF NOT EXISTS `biografo_imaginario`.`questions` (
  `objects_id` INT NOT NULL,
  `users_username` VARCHAR(45) NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`objects_id`, `users_username`),
  INDEX `fk_objects_has_users_users1_idx` (`users_username` ASC) VISIBLE,
  INDEX `fk_objects_has_users_objects1_idx` (`objects_id` ASC) VISIBLE,
  CONSTRAINT `fk_objects_has_users_objects1`
    FOREIGN KEY (`objects_id`)
    REFERENCES `biografo_imaginario`.`objects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objects_has_users_users1`
    FOREIGN KEY (`users_username`)
    REFERENCES `biografo_imaginario`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biografo_imaginario`.`objects_has_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biografo_imaginario`.`objects_has_tags` ;

CREATE TABLE IF NOT EXISTS `biografo_imaginario`.`objects_has_tags` (
  `objects_id` INT NOT NULL,
  `tags_name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`objects_id`, `tags_name`),
  INDEX `fk_objects_has_tags_tags1_idx` (`tags_name` ASC) VISIBLE,
  INDEX `fk_objects_has_tags_objects1_idx` (`objects_id` ASC) VISIBLE,
  CONSTRAINT `fk_objects_has_tags_objects1`
    FOREIGN KEY (`objects_id`)
    REFERENCES `biografo_imaginario`.`objects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objects_has_tags_tags1`
    FOREIGN KEY (`tags_name`)
    REFERENCES `biografo_imaginario`.`tags` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biografo_imaginario`.`videos_has_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biografo_imaginario`.`videos_has_tags` ;

CREATE TABLE IF NOT EXISTS `biografo_imaginario`.`videos_has_tags` (
  `videos_id` INT NOT NULL,
  `tags_name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`videos_id`, `tags_name`),
  INDEX `fk_videos_has_tags_tags1_idx` (`tags_name` ASC) VISIBLE,
  INDEX `fk_videos_has_tags_videos1_idx` (`videos_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_has_tags_videos1`
    FOREIGN KEY (`videos_id`)
    REFERENCES `biografo_imaginario`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videos_has_tags_tags1`
    FOREIGN KEY (`tags_name`)
    REFERENCES `biografo_imaginario`.`tags` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

FLUSH PRIVILEGES ;